#!/bin/bash 

pdftk full-pdf.pdf cat 1 output out_1.pdf
pdftk full-pdf.pdf cat 2 output out_2.pdf
pdftk full-pdf.pdf cat 3 output out_3.pdf
pdftk full-pdf.pdf cat 4 output out_4.pdf
pdftk full-pdf.pdf cat 5 output out_5.pdf
pdftk full-pdf.pdf cat 6 output out_6.pdf
pdftk full-pdf.pdf cat 7 output out_7.pdf
pdftk full-pdf.pdf cat 8 output out_8.pdf
pdftk full-pdf.pdf cat 9 output out_9.pdf
pdftk full-pdf.pdf cat 10 output out_10.pdf
pdftk full-pdf.pdf cat 11 output out_11.pdf
pdftk full-pdf.pdf cat 12 output out_12.pdf
pdftk full-pdf.pdf cat 13 output out_13.pdf
pdftk full-pdf.pdf cat 14 output out_14.pdf
pdftk full-pdf.pdf cat 15 output out_15.pdf
pdftk full-pdf.pdf cat 16 output out_16.pdf
pdftk full-pdf.pdf cat 17 output out_17.pdf
pdftk full-pdf.pdf cat 18 output out_18.pdf
pdftk full-pdf.pdf cat 19 output out_19.pdf
pdftk full-pdf.pdf cat 20 output out_20.pdf
pdftk full-pdf.pdf cat 21 output out_21.pdf
pdftk full-pdf.pdf cat 22 output out_22.pdf
pdftk full-pdf.pdf cat 23 output out_23.pdf
pdftk full-pdf.pdf cat 24 output out_24.pdf
pdftk full-pdf.pdf cat 25 output out_25.pdf
pdftk full-pdf.pdf cat 26 output out_26.pdf
pdftk full-pdf.pdf cat 27 output out_27.pdf
pdftk full-pdf.pdf cat 28 output out_28.pdf
pdftk full-pdf.pdf cat 29 output out_29.pdf
pdftk full-pdf.pdf cat 30 output out_30.pdf
pdftk full-pdf.pdf cat 31 output out_31.pdf
pdftk full-pdf.pdf cat 32 output out_32.pdf
pdftk full-pdf.pdf cat 33 output out_33.pdf
pdftk full-pdf.pdf cat 34 output out_34.pdf
pdftk full-pdf.pdf cat 35 output out_35.pdf
pdftk full-pdf.pdf cat 36 output out_36.pdf
pdftk full-pdf.pdf cat 37 output out_37.pdf
pdftk full-pdf.pdf cat 38 output out_38.pdf
pdftk full-pdf.pdf cat 39 output out_39.pdf
pdftk full-pdf.pdf cat 40 output out_40.pdf
pdftk full-pdf.pdf cat 41 output out_41.pdf
pdftk full-pdf.pdf cat 42 output out_42.pdf
pdftk full-pdf.pdf cat 43 output out_43.pdf
pdftk full-pdf.pdf cat 44 output out_44.pdf
pdftk full-pdf.pdf cat 45 output out_45.pdf
pdftk full-pdf.pdf cat 46 output out_46.pdf
pdftk full-pdf.pdf cat 47 output out_47.pdf
pdftk full-pdf.pdf cat 48 output out_48.pdf
pdftk full-pdf.pdf cat 49 output out_49.pdf
pdftk full-pdf.pdf cat 50 output out_50.pdf
pdftk full-pdf.pdf cat 51 output out_51.pdf
pdftk full-pdf.pdf cat 52 output out_52.pdf
pdftk full-pdf.pdf cat 53 output out_53.pdf
pdftk full-pdf.pdf cat 54 output out_54.pdf
pdftk full-pdf.pdf cat 55 output out_55.pdf
pdftk full-pdf.pdf cat 56 output out_56.pdf
pdftk full-pdf.pdf cat 57 output out_57.pdf
pdftk full-pdf.pdf cat 58 output out_58.pdf
pdftk full-pdf.pdf cat 59 output out_59.pdf
pdftk full-pdf.pdf cat 60 output out_60.pdf
pdftk full-pdf.pdf cat 61 output out_61.pdf
pdftk full-pdf.pdf cat 62 output out_62.pdf
pdftk full-pdf.pdf cat 63 output out_63.pdf
pdftk full-pdf.pdf cat 64 output out_64.pdf
pdftk full-pdf.pdf cat 65 output out_65.pdf
pdftk full-pdf.pdf cat 66 output out_66.pdf
pdftk full-pdf.pdf cat 67 output out_67.pdf
pdftk full-pdf.pdf cat 68 output out_68.pdf
pdftk full-pdf.pdf cat 69 output out_69.pdf
pdftk full-pdf.pdf cat 70 output out_70.pdf
pdftk full-pdf.pdf cat 71 output out_71.pdf
pdftk full-pdf.pdf cat 72 output out_72.pdf
pdftk full-pdf.pdf cat 73 output out_73.pdf
pdftk full-pdf.pdf cat 74 output out_74.pdf
pdftk full-pdf.pdf cat 75 output out_75.pdf
pdftk full-pdf.pdf cat 76 output out_76.pdf
pdftk full-pdf.pdf cat 77 output out_77.pdf
pdftk full-pdf.pdf cat 78 output out_78.pdf
pdftk full-pdf.pdf cat 79 output out_79.pdf
pdftk full-pdf.pdf cat 80 output out_80.pdf
pdftk full-pdf.pdf cat 81 output out_81.pdf
